### ISSUE TITLE
Latest image built by Docker Hub errors out

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#175]
# Details

The `0.3.3` tagged version does not have this issue, but the `latest` image auto-built from commit 7fabf12 did.  Verified error on laptop and external server with same issue.  Only the image built by Docker Hub appears to have the issue, image built locally does not error out.  For now I have disabled the auto-build on docker hub and will manually build/push.

Did something change in Docker hub possibly?

----

## Logs

Running the standard example I ran into this error from `docker exec`.

```
Traceback (most recent call last):
  File "/app/docker/pgosm_flex.py", line 637, in <module>
    run_pgosm_flex()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/docker/pgosm_flex.py", line 120, in run_pgosm_flex
    run_osm2pgsql(osm2pgsql_command=osm2pgsql_command, paths=paths)
  File "/app/docker/pgosm_flex.py", line 600, in run_osm2pgsql
    output = subprocess.run(osm2pgsql_command.split(),
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['osm2pgsql', '-d', 'postgresql://postgres:mysecretpassword@localhost/pgosm?application_name=pgosm-flex', '--output=flex', '--style=./run-all.lua', '/app/output/district-of-columbia-latest.osm.pbf']' returned non-zero exit status 127.
```

Checking `docker logs pgosm` shows:

```
2021-09-28 13:22:15.475 MDT [201] FATAL:  role "root" does not exist
2021-09-28 13:22:20.526 MDT [203] FATAL:  role "root" does not exist
2021-09-28 13:22:22.504 MDT [213] ERROR:  relation "changes" does not exist at character 689
2021-09-28 13:22:22.504 MDT [213] STATEMENT:  
	        SELECT c.change_id
	             , c.script_hash
	                 , c.change
	             , c.project
	             , c.note
	             , c.committer_name
	             , c.committer_email
	             , to_char(c.committed_at AT TIME ZONE 'UTC', '"year":YYYY:"month":MM:"day":DD:"hour":HH24:"minute":MI:"second":SS:"time_zone":"UTC"') AS committed_at
	             , c.planner_name
	             , c.planner_email
	             , to_char(c.planned_at AT TIME ZONE 'UTC', '"year":YYYY:"month":MM:"day":DD:"hour":HH24:"minute":MI:"second":SS:"time_zone":"UTC"') AS planned_at
	             , ARRAY(SELECT * FROM UNNEST( array_agg(t.tag) ) a WHERE a IS NOT NULL) AS tags
	          FROM changes   c
	          LEFT JOIN tags t ON c.change_id = t.change_id
	         WHERE c.project = $1
	         GROUP BY c.change_id
	             , c.script_hash
	                 , c.change
	             , c.project
	             , c.note
	             , c.committer_name
	             , c.committer_email
	             , c.committed_at
	             , c.planner_name
	             , c.planner_email
	             , c.planned_at
	         ORDER BY c.committed_at DESC
	         LIMIT 1
	    
2021-09-28 13:22:22.508 MDT [213] WARNING:  Sqitch registry not initialized
2021-09-28 13:22:22.508 MDT [213] DETAIL:  Because the "changes" table does not exist, Sqitch will now initialize the database to create its registry tables.
2021-09-28 13:22:22.508 MDT [213] CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
```

I re-tested Docker Hub's build by manually triggering a build and it had the same error.  Pushed an updated version from local build, no issue.

**Comment by rustprooflabs** [comment]
I have little interest in spending time to fix this.  I'm already building locally, pushing the new images isn't a big deal...
